### ISSUE TITLE
1.5.0 build error on RHEL 6

### ISSUE THREAD

**Issue by devrimgunduz** [postgrespro/pg_pathman#178] opened 2018-09-24 20:07 UTC
Hi,

Getting this while building 1.5.0 on RHEL 6:

> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC -I/home/pgsql/rpm11testing/BUILD/pg_pathman-1.5.0/src/include -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal -I/usr/include -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o src/rangeset.o src/rangeset.c
> src/pg_pathman.c: In function 'append_child_relation':
> src/pg_pathman.c:539: error: 'PlannerInfo' has no member named 'append_rel_array'
> make[1]: *** [src/pg_pathman.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
>

**Comment by ildus** [comment] 2018-09-25 09:35
duplicate of #177

**Closed by ildus** 2018-09-25 09:35 UTC
