### ISSUE TITLE
pg_dump not working with partitioned table: improper qualified name (too many dotted names)

### ISSUE THREAD

**Issue by Envek** [postgrespro/pg_pathman#50] opened 2016-10-26 06:38 UTC
Executing command (DB server is on the same machine):

```
pg_dump -F custom database > new_shiny.dump
```

Getting error:

```
pg_dump: [archiver (db)] query failed: ERROR:  improper qualified name (too many dotted names): id.tracker_id.data.evented_at.created_at.ambulance_status_id.in_zone.is_stop
LINE 1: COPY public.tracker_points (id, tracker_id, data, evented_at...
         ^
pg_dump: [archiver (db)] query was: COPY public.tracker_points (id, tracker_id, data, evented_at, created_at, ambulance_status_id, in_zone, is_stop) TO stdout;
```

And pg_dump is immediately finished with non-zero exit code.

Where `id.tracker_id.data.evented_at.created_at.ambulance_status_id.in_zone.is_stop` is just a list of columns of `tracker_points` table joined with dot.

PostgreSQL 9.5.4 with pg_pathman 1.1, 1.1.1 and `master_improved_planning` branch.

Database is the same as in https://github.com/postgrespro/pg_pathman/issues/41

**Comment by funbringer** [comment] 2016-10-26 08:09
Try this on a clean DB (without pg_pathman or anything):

```plpgsql
create roly dummy with login;
create table mk(a int, b int, c int, d int, e int);
create policy p_1 on mk for select using(true);
alter table mk enable row level security;
grant select on mk to dummy;
```

Now as `dummy`:

```plpgsql
copy mk(a,b,c,d, e) to stdout;
ERROR:  improper qualified name (too many dotted names): a.b.c.d.e
LINE 1: copy mk(a,b,c,d, e) to stdout;

copy mk(a,b,c,d) to stdout;
ERROR:  cross-database references are not implemented: a.b.c.d
LINE 1: copy mk(a,b,c,d) to stdout;
```

This makes me sad.

**Comment by Envek** [comment] 2016-10-26 12:31
Well, we're not using RLS and dump is performed by the owner of DB.

pg_dump stopped working after table partitioning with pg_pathman (pg_pathman was installed couple of days before that, but wasn't used).

So it seems to be caused by some pg_pathman internal work on parent table. `COPY` from partitions works well (so it's not critical as parent table eventually become empty).

As a workaround, specifying `--exclude-table-data` for parent table is working for me:

    pg_dump -F custom database --exclude-table-data=tracker_points

**Comment by funbringer** [comment] 2016-10-26 12:48
> pg_dump stopped working after table partitioning with pg_pathman

The thing is that pg_pathman requires some machinery that appears to be broken in PostgreSQL, not pg_pathman. We have to replace `copy table to..` with something like `copy (select * from table) to` to pick up data from partitions.

This rewriting process also takes place when a table is protected by RLS, so I've deliberately shown you a query that reveals the bug in PostgreSQL core.

See for yourself: [hackers thread](https://www.postgresql.org/message-id/CAE_9P%3Di9ZWrTJ-b2VgRPsT9-qLeQ9EwHeWLFimsjtuZKqnSnng%40mail.gmail.com). I think the fix is going to be back-ported.

**Comment by funbringer** [comment] 2016-10-26 13:13
Now that I've read this thread more carefully, I think I might fix this in pg_pathman. I'll report when I have results.

**Comment by funbringer** [comment] 2016-10-26 14:23
I've pushed a fix to master branch and some other ones, including the `master_improved_planning`. Thank you for your bug report and especially for your confidence! At first, I didn't bother to get into details of this bug, because I knew about it and it had already been tracked by someone else. A patch from the hackers thread fixes the code that we borrowed for our own needs, so I was able to apply it and fix the bug.

**Comment by Envek** [comment] 2016-10-26 19:02
Checked version from `master_improved_planning` branch and `pg_dump` finished without errors, but resulted dump file is smaller than I expected, so restoring from dump to another db and checking `COUNT`s for tables (most probably I've deleted a lot of data from my local database during various experiments).

**Comment by Envek** [comment] 2016-10-31 06:34
1. `set_enable_parent` is affecting results of `pg_dump`. If set to `false` then not yet transferred data from parent table is ignored (not dumped: source dump was 8.7 GB, resulted is 3.9 GB). That's  not expected behavior for pg_dump. 
 2. When restoring the backup with `pg_restore` all data from parent table is transferred to partitions. Hard to say whether this is a feature or a bug 😄 

When restoring dump, created with `set_enable_parent` set to `true`, I've got a few errors about duplicating ids in some partitions (4 errors for 17 partitions with data):

```
pg_restore: [archiver (db)] Error from TOC entry 4533; 2606 6968367 CONSTRAINT tracker_points_2016_01_pkey smp
pg_restore: [archiver (db)] could not execute query: ERROR:  could not create unique index "tracker_points_2016_01_pkey"
DETAIL:  Key (id)=(3b0c438d-61bc-4880-857d-cb9d86f9dd39) is duplicated.
    Command was: ALTER TABLE ONLY tracker_points_2016_01
    ADD CONSTRAINT tracker_points_2016_01_pkey PRIMARY KEY (id);
```

And that's absolutely unexpected. There surely was no duplicating primary keys.

And main thing: **`COUNT`s not matching after restore**

Source database — have partially range-partitioned table `tracker_points` by timestamp column `evented_at`: 

```
smp=# SELECT COUNT(*) FROM tracker_points;
   count
-----------
 117850479
(1 row)

smp=# SELECT COUNT(*) FROM ONLY tracker_points;
   count
-----------
 103086479
(1 row)

smp=# SELECT COUNT(*) FROM tracker_points_2016_10;
  count
---------
 4241472
(1 row)
```

Destination database — got from source database with `pg_dump -F custom src > src.dump` and `pg_restore -F custom -d dst src.dump`:

```
# SELECT COUNT(*) FROM tracker_points;
   count
-----------
 132614479
(1 row)

# SELECT COUNT(*) FROM ONLY tracker_points;
 count
-------
     0
(1 row)

# SELECT COUNT(*) FROM tracker_points_2016_10;
  count
----------
 12807701
(1 row)
```

**Comment by funbringer** [comment] 2016-10-31 17:23
> `set_enable_parent` is affecting results of pg_dump.

This may sound strange, but it's supposed to work that way. This allows user to dump\copy only contents of partitions and exclude data that's to be partitioned yet (stored in parent). Nonetheless, I agree that this is not immediately obvious.

> When restoring the backup with `pg_restore` all data from parent table is transferred to partitions. Hard to say whether this is a feature or a bug

Perhaps you could call it a feature. Apparently, `pg_restore` utilizes our `INSERT \ COPY` machinery which redirects tuples to partitions. We had no intention to provide any workarounds for this specific case.

> I've got a few errors about duplicating ids in some partitions.

pg_pathman overrides `COPY TO \ FROM` and `SELECT * FROM` statements by default, which means that you might get a wrong dump containing duplicate data if you include partitions OR at least don't disable pg_pathman beforehand. While this might look ugly, there's not much we can do about it. Extensions will always be just extensions, we can't control all aspects of PostgreSQL.

In order to disable our hooks and machinery, you can always use `pg_pathman.enable` and `pg_pathman.override_copy` GUCs before running `pg_dump`. They will help you restore original PostgreSQL behavior.

> And main thing: **COUNTs not matching after restore**

Sorry, but I can't reproduce your problem. I'll try again later after I've finished my current tasks. Stay tuned.

**Comment by maksm90** [comment] 2016-11-22 10:57
Hi, @Envek !

I tried to reproduce your situation on a test sample - partitioned table with primary key filled with data part of which is located in parent table, the rest - in child tables. As @funbringer mentioned, pg_pathman overrides COPY TO \ FROM and SELECT * FROM statements therefore you have to set GUC `pg_pathman.override_copy` on server level to false. That is, you have to execute: 

1. `set pg_pathman.override_copy to off`
2. Either restart postgres or send SIGHUP to postmaster (i.e. `kill -s SIGHUP <postmaster_pid>`)

After that, you'll get standard behavior of COPY in pg_dump.

In my test sample everything seems to work correctly. You could give us a feedback according to your results.

Thanks for your comprehensive description of the problem. We'll add your case to our regression test suite.

**Closed** 2016-11-30 13:14 UTC
Labels: bug

**Comment by funbringer** [comment] 2017-10-31 09:45
We decided to disable `COPY ... TO` statement in 1.4.8:

```plpgsql
copy test to stdout;
WARNING:  COPY TO will only select rows from parent table "test"
HINT:  Consider using the COPY (SELECT ...) TO variant.
```

You won't need to use `pg_pathman.override_copy` anymore to make pg_dump work as expected.
