### ISSUE TITLE
"ERROR:  XX000: could not open relation with OID" when merge partitions

### ISSUE THREAD

**Issue by killua001** [postgrespro/pg_pathman#120] opened 2017-08-31 09:02 UTC
## Partition infomation:
 parent  |  partition   | parttype | partattr |      range_min      |      range_max      
---------|--------------|----------|----------|---------------------|---------------------
 journal | journal_5    |        2 | dt       | 2017-01-01 00:20:00 | 2017-01-01 00:25:00
 journal | journal_6    |        2 | dt       | 2017-01-01 00:25:00 | 2017-01-01 00:30:00

## In session 1, merge partition #5 & #6:
```bash
[xxxx@xxx:54xx/k1 M] [08-31.16:35:17]=# begin;
BEGIN
Time: 0.221 ms
[xxxx@xxx:54xx/k1 M] [08-31.16:35:24]=# select merge_range_partitions('journal_5','journal_6');
 merge_range_partitions 
------------------------
 
(1 row)

Time: 244.467 ms
```
## In session 2, do a select: 
```bash
select count(*) from journal where dt between '2017-01-01 00:20:00' and '2017-01-01 00:30:00';
```

## End transaction in session 1:
```bash
[xxxx@xxx:54xx/k1 M] [08-31.16:38:23]=# end;
COMMIT
Time: 39.572 ms
```
## ERROR in session 2:
ERROR:  XX000: could not open relation with OID 166068
LOCATION:  relation_open, heapam.c:1066

##  Should lock parent table with ACCESS EXCLUSIVE mode when merge/drop partition ?

**Comment by funbringer** [comment] 2017-08-31 10:35
Hi @killua001,

I couldn't reproduce this behavior:

```plpgsql
/* session #1 */
issue_120=# begin;
BEGIN

select merge_range_partitions('journal_5','journal_6');
 merge_range_partitions
------------------------

(1 row)


/* session #2 */
select count(*) from journal where dt between '2017-01-01 00:20:00' and '2017-01-01 00:30:00';


/* session #1 */
commit;
COMMIT


/* session #2 */
select count(*) from journal where dt between '2017-01-01 00:20:00' and '2017-01-01 00:30:00';
 count
-------
   301
(1 row)
```

Is it 1.4.3 that you're using?

**Comment by killua001** [comment] 2017-08-31 10:41
I'am using 1.3

**Comment by funbringer** [comment] 2017-08-31 10:41
This issue has been fixed in 1.4.

**Comment by killua001** [comment] 2017-08-31 10:45
ok, Thank you.

**Comment by funbringer** [comment] 2017-08-31 10:48
> Should lock parent table with ACCESS EXCLUSIVE mode when merge/drop partition ?

Yes, that's why we had to add a few locks in `append_child_relation()`:

```C
/* Choose a correct lock mode */
if (parent_rti == root->parse->resultRelation)
	lockmode = RowExclusiveLock;
else if (parent_rowmark && RowMarkRequiresRowShareLock(parent_rowmark->markType))
	lockmode = RowShareLock;
else
	lockmode = AccessShareLock;

/* Acquire a suitable lock on partition */
LockRelationOid(child_oid, lockmode);
```

```plpgsql
select pid, relation::regclass, mode, granted from pg_locks
where mode = 'AccessExclusiveLock' and relation is not null;
  pid  |           relation            |        mode         | granted 
-------+-------------------------------+---------------------+---------
 30429 | pg_toast.pg_toast_79601       | AccessExclusiveLock | t
 30429 | journal_6                     | AccessExclusiveLock | t
 30429 | journal_5                     | AccessExclusiveLock | t
 30429 | pg_toast.pg_toast_79601_index | AccessExclusiveLock | t
(4 rows)
```

**Closed** 2017-08-31 10:50 UTC
Labels: cannot reproduce
