### ISSUE TITLE
disable_parent() sometimes does not exclude parent table from plan

### ISSUE THREAD

**Issue by digoal** [postgrespro/pg_pathman#34] opened 2016-09-27 11:42 UTC
```
postgres=# create table test(id int primary key, info text, crt_time timestamp);
CREATE TABLE
postgres=# select create_range_partitions('test'::regclass, 'id', 1, 20000000, 100, false);
 create_range_partitions 
-------------------------
                     100
(1 row)

postgres=# select disable_parent('test'::regclass);
 disable_parent 
----------------
 
(1 row)

postgres=# explain select * from test where id=1;
                                   QUERY PLAN                                    
---------------------------------------------------------------------------------
 Append  (cost=0.00..2.17 rows=2 width=44)
   ->  Seq Scan on test  (cost=0.00..0.00 rows=1 width=44)
         Filter: (id = 1)
   ->  Index Scan using test_1_pkey on test_1  (cost=0.15..2.17 rows=1 width=44)
         Index Cond: (id = 1)
(5 rows)
```

when i reconnect  
```
postgres=# \q
-> psql
psql (9.6rc1)
Type "help" for help.

postgres=# explain select * from test where id=1;
                                   QUERY PLAN                                    
---------------------------------------------------------------------------------
 Append  (cost=0.15..2.17 rows=1 width=44)
   ->  Index Scan using test_1_pkey on test_1  (cost=0.15..2.17 rows=1 width=44)
         Index Cond: (id = 1)
(3 rows)
```

**Comment by funbringer** [comment] 2016-09-27 14:46
Hi @digoal,

This seems to be fixed in one of our dev branches, or at least I can't reproduce this behavior on my installation. Anyway, release 1.1 is coming soon, so you'll have a chance to give it a try.

**Closed** 2016-10-26 19:45 UTC
Labels: cannot reproduce
