### ISSUE TITLE
ERROR: must be superuser to examine "shared_preload_libraries"

### ISSUE THREAD

**Issue by killua001** [postgrespro/pg_pathman#82] opened 2017-03-27 05:37 UTC
When run sql to delete data from the partition table:
delete from ubas_event_info_his_20170327 a where a.data_source not in ('ios','android')

Error raise：
Caused by: org.postgresql.util.PSQLException: ERROR: must be superuser to examine "shared_preload_libraries"

postgresql.conf：
shared_preload_libraries = 'pg_pathman,repmgr_funcs,pg_stat_statements,auto_explain'

**Comment by funbringer** [comment] 2017-03-27 08:10
Hi @killua001,

Thank you for your bug report. In fact, pg_pathman is supposed to show you this message:

```
ERROR: extension conflict has been detected
DETAIL: shared_preload_libraries = "pg_pathman,repmgr_funcs,pg_stat_statements,auto_explain"
HINT: pg_pathman should be the last extension listed in shared_preload_libraries GUC
in order to prevent possible conflicts with other extensions
```

We'll fix this in no time, but you definitely should follow this hint.

**Comment by killua001** [comment] 2017-03-27 08:31
Thank you

**Comment by funbringer** [comment] 2017-03-27 12:32
Pushed a fix into `master` branch.

**Comment by killua001** [comment] 2017-04-06 08:31
Hi, Funbringer,
After I change the shared_preload_libraries parameter to 
**_shared_preload_libraries = 'repmgr_funcs,pg_stat_statements,auto_explain,pg_pathman'_**

The error "ERROR: must be superuser to examine "shared_preload_libraries"  still there.

Can I download the master branch now, or  will you provided a hot fix release?

**Comment by funbringer** [comment] 2017-04-06 09:23
to @killua001:

> Can I download the master branch now, or will you provided a hot fix release?

Could you try a `master` branch? I'll release a hotfix release if it works for you.

**Comment by killua001** [comment] 2017-04-07 03:22
I will try the master branch, and run it for one week.
Thank you.

**Comment by tarvip** [comment] 2017-04-18 15:35
README says that `pg_pathman` must be first if using together with `pg_stat_statements`, but HINT says it should be last, which one is correct?

**Comment by funbringer** [comment] 2017-04-18 16:42
to @tarvip:

Thanks, I've fixed readme. Sometimes it's hard to track changes.

pg_pathman should be the last extension.

**Comment by funbringer** [comment] 2017-04-18 16:45
to @killua001:

Is everything ok now?

**Comment by killua001** [comment] 2017-04-25 08:37
@funbringer 
There is no error until now. May be the bug has been fixed .

**Comment by funbringer** [comment] 2017-04-25 09:07
@killua001:

Ok, feel free to write us if anything is wrong. You'll be able to post messages in this thread even if the issue is closed.

**Closed by funbringer** 2017-04-25 09:07 UTC
Labels: bug, help wanted

**Comment by killua001** [comment] 2017-04-25 13:06
@funbringer 
Will you release a new version to fix this bug?

**Comment by funbringer** [comment] 2017-04-25 13:23
I think we'll roll out a bugfix release in 1-2 days (1.3.1).

**Comment by killua001** [comment] 2017-04-26 03:19
@funbringer 
Thank you!
